In [1]:
import torch

In [3]:
l, m, n, k = 32, 512, 512, 512
a = torch.randint(-128, 128, (l, m, k//2), dtype=torch.int8).permute(1,2,0)
a.shape

torch.Size([512, 256, 32])

In [4]:
a.view(torch.float4_e2m1fn_x2).shape

torch.Size([512, 256, 32])

In [3]:
i_idx = torch.arange(3,)
j_idx = torch.arange(3)

# Create meshgrid for all combinations of (i, j, b)
i_grid, j_grid = torch.meshgrid(i_idx, j_idx, indexing='ij')

In [4]:
i_grid

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])

In [5]:
j_grid

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])

In [ ]:
b_grid

tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]], device='cuda:0')

: 