In [1]:
import torch

In [3]:
l, m, n, k = 32, 512, 512, 512
a = torch.randint(-128, 128, (l, m, k//2), dtype=torch.int8).permute(1,2,0)
a.shape

torch.Size([512, 256, 32])

In [4]:
a.view(torch.float4_e2m1fn_x2).shape

torch.Size([512, 256, 32])

In [6]:
import torch
test = torch.randint(0, 128, (10,), dtype=torch.int8, device='cuda')
print("Int8 values:", test)
test_fp8 = test.to(dtype=torch.float8_e4m3fn)
print("FP8 values:", test_fp8.to(torch.float32))  # Convert to FP32 to see actual values

Int8 values: tensor([ 80,  15,  31,   3,  59, 107,  34, 108,  41,  50], device='cuda:0',
       dtype=torch.int8)
FP8 values: tensor([ 80.,  15.,  32.,   3.,  60., 104.,  32., 112.,  40.,  48.],
       device='cuda:0')


In [7]:
i_idx = torch.arange(3, device='cuda')
j_idx = torch.arange(3, device='cuda')
b_idx = torch.arange(3, device='cuda')

# Create meshgrid for all combinations of (i, j, b)
i_grid, j_grid, b_grid = torch.meshgrid(i_idx, j_idx, b_idx, indexing='ij')

In [8]:
i_grid

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]], device='cuda:0')

In [9]:
j_grid

tensor([[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]]], device='cuda:0')

In [10]:
b_grid

tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]], device='cuda:0')